services:
  database:
    image: postgres:17
    container_name: db
    volumes:
      - psql_volume:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  api:
    image: ecommerce/api
    container_name: api
    ports:
      - 5000:5000
    depends_on:
      - database
  web:
    image: ecommerce/web
    container_name: web
    ports:
      - 3000:3000
      
volumes:
  psql_volume: