FROM python:3.13.0

WORKDIR /app 

COPY /api/requirements.txt .

RUN pip install -r requirements.txt

COPY /api/requirements-dev.txt .

RUN pip install -r requirements-dev.txt

COPY /api .

EXPOSE 5000

CMD ["gunicorn", "-w", "4", "--reload", "--bind", "0.0.0.0:5000", "ecommerce:app"]