import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import CartProvider from '@/context/CartContext'
import { Kanit, Montserrat } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Ecommerce',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  weight: ['400', '400', '600'],
  subsets: ['latin'],
  variable: '--font-montserrat',
})

const kanit = Kanit({
  weight: ['500', '600'],
  subsets: ['latin'],
  variable: '--font-kanit',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className={`${montserrat.variable} ${kanit.variable}`} lang="en">
      <body className={'antialiased bg-neutral-200 font-sans'}>
        <CartProvider>
          <Header />
          {children}
        </CartProvider>
      </body>
    </html>
  )
}
