"""change product.categories mapping

Revision ID: 65ce6f2cf789
Revises: 7a36af68cf51
Create Date: 2025-02-11 14:42:17.112211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ce6f2cf789'
down_revision: Union[str, None] = '7a36af68cf51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
