"""add more columns to products table

Revision ID: f7dd0de0429e
Revises: 60f93139e0e6
Create Date: 2025-02-06 14:23:07.089544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7dd0de0429e'
down_revision: Union[str, None] = '60f93139e0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.String(), nullable=False))
    op.add_column('products', sa.Column('category', sa.String(), nullable=False))
    op.add_column('products', sa.Column('price', sa.String(), nullable=False))
    op.add_column('products', sa.Column('model', sa.String(), nullable=True))
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    op.drop_column('products', 'model')
    op.drop_column('products', 'price')
    op.drop_column('products', 'category')
    op.drop_column('products', 'name')
    # ### end Alembic commands ###
