# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      working-directory: ./api
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Check linting with ruff
      working-directory: ./api
      run: |
        ruff check boss_tracker

    - name: Check code formatting with black
      working-directory: ./api
      run: |
        black --check boss_tracker

    - name: Check typing with mypy
      working-directory: ./api
      run: |
        mypy boss_tracker
        
    - name: Setup testing database 
      working-directory: ./api
      run: |
        make setup_test_db
    - name: Test with pytest
      working-directory: ./api
      run: |
        pytest
        