# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: uv sync

    - name: Check linting with ruff
      working-directory: ./api
      run: |
        uv run ruff check ecommerce

    - name: Check code formatting with black
      working-directory: ./api
      run: |
        uv run black --check ecommerce

    - name: Check typing with mypy
      working-directory: ./api
      run: |
        uv run mypy ecommerce
        
    - name: Test with pytest
      working-directory: ./api
      run: |
        uv run pytest
        